---
description: "Obtener más información acerca de: ' Catch ' no puede aparecer fuera de una instrucción ' Try '"
title: "'Catch' no puede aparecer fuera de una instrucción 'Try'."
ms.date: 07/20/2015
f1_keywords:
- bc30380
- vbc30380
helpviewer_keywords:
- BC30380
ms.assetid: 73ce950d-881f-4532-8024-40a4930abd32
ms.openlocfilehash: 4ac18a51602c7dc5c4d7b397e1b64f9ed77fcc87
ms.sourcegitcommit: 10e719780594efc781b15295e499c66f316068b8
ms.translationtype: MT
ms.contentlocale: es-ES
ms.lasthandoff: 02/14/2021
ms.locfileid: "100473906"
---
# <a name="catch-cannot-appear-outside-a-try-statement"></a>'Catch' no puede aparecer fuera de una instrucción 'Try'.

`Catch` debe aparecer dentro de un bloque de instrucciones `Try...Catch...Finally` . O bien hay una instrucción `Catch` innecesaria en su bloque `Try` , o la instrucción `Catch` aparece fuera de los límites de su bloque `Try` correspondiente.  
  
 **Identificador de error:** BC30380  
  
## <a name="to-correct-this-error"></a>Para corregir este error  
  
1. Elimine la instrucción `Catch` si es innecesaria, o colóquela en un bloque de instrucciones `Try...Catch...Finally` .  
  
## <a name="see-also"></a>Vea también

- [Try...Catch...Finally (instrucción)](../language-reference/statements/try-catch-finally-statement.md)
