---
description: "Más información acerca de: la instrucción ' Throw ' no puede omitir el operando fuera de una instrucción ' Catch ' o dentro de una instrucción ' Finally '"
title: La instrucción 'Throw' no puede omitir el operando fuera de una instrucción 'Catch' o dentro de una instrucción 'Finally'
ms.date: 07/20/2015
f1_keywords:
- vbc30666
- bc30666
helpviewer_keywords:
- BC30666
ms.assetid: a208a6ea-0e36-4bf1-8984-4de1a0e38a2a
ms.openlocfilehash: 8ab76ae9e5727388ddb77ec38f1b4e89b6a0e5d6
ms.sourcegitcommit: 10e719780594efc781b15295e499c66f316068b8
ms.translationtype: MT
ms.contentlocale: es-ES
ms.lasthandoff: 02/14/2021
ms.locfileid: "100460844"
---
# <a name="throw-statement-cannot-omit-operand-outside-a-catch-statement-or-inside-a-finally-statement"></a><span data-ttu-id="9756b-103">La instrucción 'Throw' no puede omitir el operando fuera de una instrucción 'Catch' o dentro de una instrucción 'Finally'</span><span class="sxs-lookup"><span data-stu-id="9756b-103">'Throw' statement cannot omit operand outside a 'Catch' statement or inside a 'Finally' statement</span></span>

<span data-ttu-id="9756b-104">Las instrucciones`Throw` fuera de una instrucción `Catch` deben facilitar el nombre de un objeto de excepción.</span><span class="sxs-lookup"><span data-stu-id="9756b-104">`Throw` statements outside of `Catch` statement must supply the name of an exception object.</span></span>  
  
 <span data-ttu-id="9756b-105">**Id. de error:** BC30666</span><span class="sxs-lookup"><span data-stu-id="9756b-105">**Error ID:** BC30666</span></span>  
  
## <a name="to-correct-this-error"></a><span data-ttu-id="9756b-106">Para corregir este error</span><span class="sxs-lookup"><span data-stu-id="9756b-106">To correct this error</span></span>  
  
1. <span data-ttu-id="9756b-107">Especifique el nombre de un objeto de excepción que derive de `System.Exception`.</span><span class="sxs-lookup"><span data-stu-id="9756b-107">Specify the name of an exception object derived from `System.Exception`.</span></span>  
  
2. <span data-ttu-id="9756b-108">Reestructure el código para que la instrucción `Throw` se encuentre dentro de un bloque `Catch` .</span><span class="sxs-lookup"><span data-stu-id="9756b-108">Restructure your code so that the `Throw` statement is inside a `Catch` block.</span></span>  
  
## <a name="see-also"></a><span data-ttu-id="9756b-109">Consulte también</span><span class="sxs-lookup"><span data-stu-id="9756b-109">See also</span></span>

- [<span data-ttu-id="9756b-110">Throw (Instrucción)</span><span class="sxs-lookup"><span data-stu-id="9756b-110">Throw Statement</span></span>](../language-reference/statements/throw-statement.md)
- [<span data-ttu-id="9756b-111">Try...Catch...Finally (instrucción)</span><span class="sxs-lookup"><span data-stu-id="9756b-111">Try...Catch...Finally Statement</span></span>](../language-reference/statements/try-catch-finally-statement.md)
- <xref:System.Exception?displayProperty=nameWithType>
- [<span data-ttu-id="9756b-112">Controlar y generar excepciones en .NET</span><span class="sxs-lookup"><span data-stu-id="9756b-112">Handling and throwing exceptions in .NET</span></span>](../../standard/exceptions/index.md)
