---
description: 'Más información sobre: System. ServiceModel. AsyncCallbackThrewException'
title: System.ServiceModel.AsyncCallbackThrewException
ms.date: 03/30/2017
ms.assetid: dfc27ca7-b904-4f29-a5b6-dc702fa54a20
ms.openlocfilehash: 53ef853d22041099eb68fe79f7ef43bc24c55798
ms.sourcegitcommit: ddf7edb67715a5b9a45e3dd44536dabc153c1de0
ms.translationtype: MT
ms.contentlocale: es-ES
ms.lasthandoff: 02/06/2021
ms.locfileid: "99644702"
---
# <a name="systemservicemodelasynccallbackthrewexception"></a><span data-ttu-id="e7a76-103">System.ServiceModel.AsyncCallbackThrewException</span><span class="sxs-lookup"><span data-stu-id="e7a76-103">System.ServiceModel.AsyncCallbackThrewException</span></span>

<span data-ttu-id="e7a76-104">System.ServiceModel.AsyncCallbackThrewException</span><span class="sxs-lookup"><span data-stu-id="e7a76-104">System.ServiceModel.AsyncCallbackThrewException</span></span>  
  
## <a name="description"></a><span data-ttu-id="e7a76-105">Descripción</span><span class="sxs-lookup"><span data-stu-id="e7a76-105">Description</span></span>  

 <span data-ttu-id="e7a76-106">Una devolución de llamada asincrónica produjo una excepción.</span><span class="sxs-lookup"><span data-stu-id="e7a76-106">An asynchronous callback threw an exception.</span></span>  
  
## <a name="see-also"></a><span data-ttu-id="e7a76-107">Vea también</span><span class="sxs-lookup"><span data-stu-id="e7a76-107">See also</span></span>

- [<span data-ttu-id="e7a76-108">Seguimiento</span><span class="sxs-lookup"><span data-stu-id="e7a76-108">Tracing</span></span>](index.md)
- [<span data-ttu-id="e7a76-109">Uso del seguimiento para solucionar problemas de su aplicación</span><span class="sxs-lookup"><span data-stu-id="e7a76-109">Using Tracing to Troubleshoot Your Application</span></span>](using-tracing-to-troubleshoot-your-application.md)
- [<span data-ttu-id="e7a76-110">Administración y diagnóstico</span><span class="sxs-lookup"><span data-stu-id="e7a76-110">Administration and Diagnostics</span></span>](../index.md)
